import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import getData from '@/utils/getData'
import getConfig from "next/config";

const { publicRuntimeConfig } = getConfig();
const apiKey = publicRuntimeConfig.NASA_API_KEY;

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {
  const data = await getData(`https://api.nasa.gov/planetary/apod?api_key=${apiKey}`);
  return {
    props: {
      data,
    },
  }
}

const Home = ({data}) => {

  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} role="main">
      <Image src={data.media_type === "image" ? data.url : "nasa-6.svg"} alt={data.title || "Nasa's logo"} fill={true} priority className={styles.image}/>
    </main>
    </>
  )
}

export default Home;